// Donors
export const GET_DONORS_SUCCESS = 'GET_DONORS_SUCCESS';
export const GET_DONOR_DETAILS_SUCCESS = 'GET_DONOR_DETAILS_SUCCESS';
export const ADD_DONOR_SUCCESS = 'ADD_DONOR_SUCCESS';
export const UPDATE_DONOR_SUCCESS = 'UPDATE_DONOR_SUCCESS';
export const DELETE_DONOR_SUCCESS = 'DELETE_DONOR_SUCCESS';

// Socket actions
export const ADD_DONOR_TO_LIST = 'ADD_DONOR_TO_LIST';
export const DELETE_DONOR_FROM_LIST = 'DELETE_DONOR_FROM_LIST';
export const UPDATE_DONOR_IN_LIST = 'UPDATE_DONOR_IN_LIST';

// Filters
export const TOGGLE_FILTER = 'TOGGLE_FILTER';

// Map View
export const SET_INITIAL_VIEW = 'SET_INITIAL_VIEW';
export const SET_INITIAL_GRAPHICS_LAYER = 'SET_INITIAL_GRAPHICS_LAYER';
